#define CHARMMOBILE_SOURCE_DIR "${CMAKE_SOURCE_DIR}"
#define CHARMMOBILE_BUILD_DIR "${CMAKE_BINARY_DIR}"
#define CHARMMOBILE_INSTALL_DIR "${CMAKE_INSTALL_PREFIX}"
#define CHARMMOBILE_DATA_DIR "${CMAKE_INSTALL_PREFIX}/${DATA_INSTALL_DIR}/Charm"
